# Generated by Django 5.0.7 on 2024-07-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
