# Generated by Django 5.0.7 on 2024-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_stu_age_student_stu_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_enroll',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
