# Generated by Django 5.0.7 on 2024-07-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_stu_enroll'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
